### ISSUE TITLE
Zaloha descriptions

### ISSUE THREAD

**Issue by padak** [keboola/app-project-backup#14]
Při záloze projektu se neuloží description konfigurace (nebo možná neobnoví?).

Tady je příklad kde je description: https://connection.keboola.com/admin/projects/3022/transformations/bucket/372001927/transformation/399746009

A tady po obnově není: https://connection.eu-central-1.keboola.com/admin/projects/401/transformations/bucket/372001927/transformation/399746009

**Comment by Halama** [comment]
jo vypadá to že jde o restore https://github.com/keboola/php-kbc-project-restore/issues/13
Ten backup jenom dumpne json s konfigurací takže tam to bude.

**Comment by ErikZigo** [comment]
Ja se na to rano podivam

**Comment by ErikZigo** [comment]
@padak Je nasazenej fix https://github.com/keboola/app-project-restore/releases/tag/1.2.2

Zkousel jsem si to ted na mym testovacim projektu a preneslo to ty atributy
